#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	bhoikfostyahya
# //	Dscription: Xray Menu Management
# //	email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
domain=$(cat /etc/xray/domain)
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
    echo -e "───────────────────────────"
    echo -e "  Add Xray/Trojan Account  "
    echo -e "───────────────────────────"
    
    read -rp "User: " -e user
    user_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
    
    if [[ ${user_EXISTS} == '1' ]]; then
        clear
        echo -e "───────────────────────────"
        echo -e "  Add Xray/Trojan Account  "
        echo -e "───────────────────────────"
        echo ""
        echo "please choose another name."
        echo ""
        echo -e "───────────────────────────"
        read -n 1 -s -r -p "Press any key to back on menu"
        menu
    fi
done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
systemctl restart xray
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
clear
echo -e "───────────────────"
echo -e "  TROJAN ACCOUNT"
echo -e "───────────────────"
echo -e "Remarks    : ${user}" 
echo -e "Host/IP    : ${domain}" 
echo -e "port       : 443" 
echo -e "Encryption : none" 
echo -e "Path       : /trojan-ws"
echo -e "ServiceName: trojan-grpc"
echo -e "───────────────────"
echo -e "Link WS   : ${trojanlink}" 
echo -e "───────────────────"
echo -e "Link GRPC : ${trojanlink1}" 
echo -e "───────────────────"
echo -e "Expired On : $exp" 
echo -e "───────────────────"
echo "" 

