#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	bhoikfostyahya
# //	Dscription: Xray Menu Management
# //	email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
domain=$(cat /etc/xray/domain)
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
    clear
    echo -e "───────────────────────────"
    echo -e "   Add Xray/Vmess Account  "
    echo -e "───────────────────────────"
    
    read -rp "User: " -e user
    CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
    
    if [[ ${CLIENT_EXISTS} == '1' ]]; then
        clear
        echo -e "───────────────────────────"
        echo -e "   Add Xray/Vmess Accoun   "
        echo -e "───────────────────────────"
        echo ""
        echo "please choose another name."
        echo ""
        echo -e "───────────────────────────"
    fi
done

uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
VMESS_WS=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
VMESS_NON_TLS=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF`
VMESS_GRPC=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`

vmesslink1="vmess://$(echo $VMESS_WS | base64 -w 0)"
vmesslink2="vmess://$(echo $VMESS_NON_TLS | base64 -w 0)"
vmesslink3="vmess://$(echo $VMESS_GRPC | base64 -w 0)"
systemctl restart xray
clear
echo -e "───────────────────"
echo -e "   VMESS ACCOUNT   "
echo -e "───────────────────"
echo -e "Remarks     : ${user}" 
echo -e "Domain      : ${domain}" 
echo -e "Port TLS    : 443" 
echo -e "Encryption  : none" 
echo -e "Path        : /vmess"
echo -e "ServiceName : vmess-grpc"
echo -e "───────────────────"
echo -e "Link TLS    : ${vmesslink1}" 
echo -e "───────────────────"
echo -e "Link NTLS   : ${vmesslink2}" 
echo -e "───────────────────"
echo -e "Link GRPC   : ${vmesslink3}" 
echo -e "───────────────────"
echo -e "Expired On : $exp" 
echo "" 

