#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	bhoikfostyahya
# //	Dscription: Xray Menu Management
# //	email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
echo -e "───────────────────────────"
echo -e "      XRAY LOG ACCOUNT     "
echo -e "───────────────────────────"
read -p "Plase input name user :" akun
cat /var/log/xray/access.log | grep -w "$akun" 
echo -e "───────────────────────────"
echo ""

