#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	bhoikfostyahya
# //	Dscription: Xray Menu Management
# //	email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
IP=$(curl -s ipv4.icanhazip.com);
HOST="$(cat /etc/xray/domain)"
DATEVPS=$(date +"%d-%B-%Y")
ISPVPS=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
GREEN="\e[92;1m"
BLUE="\033[36m"
RED='\033[0;31m'
NC='\033[0m'

function QUESTION() {
    clear
    echo -e ""
    echo -e "${RED}WARNING !!!"
    echo -e ""
    echo -e "${RED}If you haven't uploaded your file, the VPN will not connect"
    echo -e "Please enter the recipient's email Vps Data Backup"
    echo -e "Remind Save Link Backup For Easy Data Restore"
    read -p "Plase Input Email : " EMAIL
    
}

function QUESTION2() {
    clear
    echo -e ""
    echo -e "${RED}WARNING !!!"
    echo -e ""
    echo -e "${RED}If you haven't uploaded your file, the VPN will not connect"
    echo -e "Please enter the recipient's email Vps Data Backup"
    echo -e "Remind Save Link Backup For Easy Data Restore"
    echo -e "Have you uploaded the backup file?"
    read -p "Plase Input Link : " DATAVPS
    
}

function BACKUPVPS() {
    mkdir -p /root/backup
    cp -r /etc/xray/config.json backup/ >/dev/null 2>&1
    cp /etc/passwd backup/
    cp /etc/group backup/
    cp /etc/shadow backup/
    cp /etc/gshadow backup/
    cp -r /var/www/html backup/html
    zip FT-${DATEVPS}.zip backup >/dev/null 2>&1
    rclone copy FT-${DATEVPS}.zip dr:BACKUPVPS/
    url=$(rclone link dr:BACKUPVPS/FT-${DATEVPS}.zip)
    id=(`echo $url | grep '^https' | cut -d'=' -f2`)
    LINKBACKUP="https://drive.google.com/u/4/uc?id=${id}&export=download"
    rm -rf *
    echo "
_______________________________________
SUCCESSFULL BACKUP YOUR VPS
Please Save The Following Data
_______________________________________
YOUR VPS IP : $IP
DOMAIN      : $HOST
DATE        : $DATEVPS
ISP         : $ISPVPS
LOCATION    : $CITY
LINK BACKUP : $LINKBACKUP
_______________________________________

© Copyright By https://github.com/rullpqh
Busines email : bhoikfostyahya@gmail.com
Report bugs   : https://t.me/bhoikfost_yahya
FighterTunnel Project
    " | mail -s "FighterTunnel Backup" $EMAIL
    clear
    echo -e "───────────────────────────"
    echo -e "SUCCESSFULL BACKUP YOUR VPS"
    echo -e "Please Save The Following Data"
    echo -e "───────────────────────────"
    echo -e "Your VPS IP : $IP"
    echo -e "DOMAIN      : $HOST"
    echo -e "DATE        : $DATEVPS"
    echo -e "ISP         : $ISPVPS"
    echo -e "LOCATION    : $CITY"
    echo -e "LINK BACKUP : $LINKBACKUP"
    echo -e "───────────────────────────"
    echo -e "${RED}Please Check your Email backup file"
    
    
}

function RESTOREVPS() {
    wget -O backup.zip "$DATAVPS" >/dev/null 2>&1
    unzip *.zip >/dev/null 2>&1
    rm -f *.zip >/dev/null 2>&1
    cd /root/backup
    cp passwd /etc/
    cp group /etc/
    cp shadow /etc/
    cp gshadow /etc/
    cp -r html /var/www/
    mv *.json /etc/xray >/dev/null
    systemctl restart xray >/dev/null 2>&1
    cd
    rm -rf *
    clear
    echo -e "───────────────────────────"
    echo -e "SUCCESSFULL RESTORE YOUR VPS"
    echo -e "Please Save The Following Data"
    echo -e "───────────────────────────"
    echo -e "Your VPS IP : $IP"
    echo -e "DOMAIN      : $HOST"
    echo -e "DATE        : $DATEVPS"
    echo -e "ISP         : $ISPVPS"
    echo -e "LOCATION    : $CITY"
    echo -e "LINK RESTORE: $LINKBACKUP"
    echo -e "───────────────────────────"
    echo -e "${RED}This feature can only be used if the previous data backup uses this script"
    echo -e "${RED}Please Reboot Vps"
    
}

echo -e "───────────────────────────"
echo -e "     BACKUP & RESTORE      "
echo -e "───────────────────────────"
echo -e ""
echo -e " 1 •  Backup Data VPS"
echo -e " 2 •  Restore Data VPS"
echo -e ""
echo -e "───────────────────────────"
echo -e ""
read -p "Select From Options [ 1 - 2 ] : " OPT_MENU
echo -e ""
case $OPT_MENU in
    1)
        QUESTION
        BACKUPVPS
    ;;
    2)
        QUESTION2
        RESTOREVPS
    ;;
    *)
        echo -e "${Red}You wrong command !${Font}"
        sleep 5
        menu
    ;;
esac
echo ""

