#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	bhoikfostyahya
# //	Dscription: Xray Menu Management
# //	email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
# COLOR VALIDATION
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[36m"
GREEN='\033[0;32m'
grenbo="\e[92;1m"
yellow='\033[0;33m'
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
WKT=$(curl -s ipinfo.io/timezone)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
cname=$(awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo)
cores=$(awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo)
freq=$(awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo)
tram=$(free -m | awk 'NR==2 {print $2}')
swap=$(free -m | awk 'NR==4 {print $2}')
up=$(uptime | awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')
clear
echo -e " $yellow┌─┐┬┌─┐┬ ┬┌┬┐┌─┐┬─┐  ┌┬┐┬ ┬┌┐┌┌┐┌┌─┐┬ $NC" 
echo -e " $yellow├┤ ││ ┬├─┤ │ ├┤ ├┬┘   │ │ │││││││├┤ │  $NC"
echo -e " $yellow└  ┴└─┘┴ ┴ ┴ └─┘┴└─   ┴ └─┘┘└┘┘└┘└─┘┴─┘$NC"
echo -e " ────────────────────────"
echo -e " [${grenbo}1${NC}] ${RED}• ${NC}Creating Vmess Account$NC"
echo -e " [${grenbo}2${NC}] ${RED}• ${NC}Delete Vmess Account$NC"
echo -e " [${grenbo}3${NC}] ${RED}• ${NC}Renew Vmess Account$NC"
echo -e " [${grenbo}4${NC}] ${RED}• ${NC}Check Vmess login Account"
echo -e " ────────────────────────"
echo -e " [${grenbo}5${NC}] ${RED}• ${NC}Creating Vless Account$NC"
echo -e " [${grenbo}6${NC}] ${RED}• ${NC}Delete Vless Account$NC"
echo -e " [${grenbo}7${NC}] ${RED}• ${NC}Renew Vless Account$NC"
echo -e " [${grenbo}8${NC}] ${RED}• ${NC}Check Vless login Account$NC"
echo -e " ────────────────────────"
echo -e " [${grenbo}9${NC}] ${RED}• ${NC}Creating Trojan Account$NC"
echo -e " [${grenbo}10${NC}]${RED}• ${NC}Delete Trojan Account$NC"
echo -e " [${grenbo}11${NC}]${RED}• ${NC}Renew Trojan Account$NC"
echo -e " [${grenbo}12${NC}]${RED}• ${NC}Check Trojan login Account$NC"
echo -e " ────────────────────────"
echo -e " [${grenbo}13${NC}]${RED}• ${NC}Creating Shdwsk Account$NC"
echo -e " [${grenbo}14${NC}]${RED}• ${NC}Delete Shdwsk Account$NC"
echo -e " [${grenbo}15${NC}]${RED}• ${NC}Renew Shdwsk Account$NC"
echo -e " [${grenbo}16${NC}]${RED}• ${NC}Check Shdwsk login Account$NC"
echo -e " ────────────────────────"
echo -e " [${grenbo}17${NC}]${RED}• ${NC}Check Bandwidth Xray$NC"
echo -e " [${grenbo}18${NC}]${RED}• ${NC}Check Log User Xray$NC"
echo -e " [${grenbo}19${NC}]${RED}• ${NC}Backup & Restore VPS$NC"
echo -e " [${grenbo}20${NC}]${RED}• ${NC}Change domain$NC"
echo -e " [${grenbo}21${NC}]${RED}• ${NC}Server Speedtest$NC"
echo -e " [${grenbo}22${NC}]${RED}• ${NC}Reboot server$NC"
echo -ne "Select From Options [ 1 - 22 ]: "; read opt
case $opt in
1) add-ws ;;
2) del-ws ;;
3) renew-ws ;;
4) cek-ws ;;
5) add-vless ;;
6) del-vless ;;
7) renew-vless ;;
8) cek-vless ;;
9) add-tr ;;
10) del-tr ;;
11) renew-tr ;;
12) cek-tr ;;
13) add-ss ;;
14) del-ss ;;
15) renew-ss ;;
16) cek-ss ;;
17) get-bw ;;
18) get-log ;;
19) get-backres ;;
20) get-domain ;;
21) speedtest-cli --share ;;
22) reboot ;;
*) menu ;;
esac